version: '3'

services:
  db:
    build: ./database
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress

  srdb:
    build: ./Search-Replace-DB
    depends_on:
      - db
      - phpma
      - wp
    restart: on-failure

  phpma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root

  wp:
    build: ./wordpress
    depends_on:
      - db
    ports:
      - "8000:80"
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root

volumes:
  db_data: